# Generated by Django 5.2.8 on 2026-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('parent', 'Parent'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
    ]
